name: testmime
description: "Assessment task for TestLine."
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ^3.6.0

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  hive: ^2.2.3
  http: ^1.2.2
  get: ^4.6.6
  flutter_launcher_icons: ^0.14.3
  hive_flutter: ^1.1.0
  lottie: ^3.3.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  hive_generator: ^2.0.1

flutter_launcher_icons:
  android: "ic_launcher"
  ios: true
  image_path: "assets/logo/logo.png"
  adaptive_icon_foreground: "assets/logo/logo.png"
  adaptive_icon_background: "#ffffffff"
  adaptive_icon_foreground_inset: 20

flutter:
  uses-material-design: true
  assets:
    - assets/images/
    - assets/logo/
    - assets/illustrations/

  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700